{"@t":"2019-03-30T15:11:21.0697421Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-03-30T15:12:19.0639197Z","@mt":"xceptionLogId:1jmsWdzL, ExceptionType:System.Exception, ExceptionInnerException:, ExceptionMessage:error occured, ExceptionSeverity:Critical Error, ExceptionFileName:C:\\Clients\\PintLab\\OERService\\OERService\\Controllers\\CategoriesController.cs, ExceptionMethodName:OERService.Controllers.CategoriesController+<Get>d__2, ExceptionLineNumber:36, ExceptionColumnNumber:17","@l":"Error","Application":"OER Service"}
{"@t":"2019-04-01T03:05:44.2232534Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T16:28:20.7854539Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T16:30:18.8349583Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T16:31:09.7597887Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T16:33:41.6661233Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T16:42:32.7317222Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T17:02:41.5597310Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T17:30:16.3251462Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T19:14:46.8093109Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T19:32:44.9106128Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T19:44:30.8187380Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T19:46:23.1845458Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-04T19:47:06.8726643Z","@mt":"xceptionLogId:61naWR6D, ExceptionType:System.Data.SqlClient.SqlException, ExceptionInnerException:, ExceptionMessage:Cannot open database \"OER\" requested by the login. The login failed.\r\nLogin failed for user 'oerpintlab'., ExceptionSeverity:Critical Error, ExceptionFileName:, ExceptionMethodName:System.Data.SqlClient.SqlInternalConnectionTds, ExceptionLineNumber:0, ExceptionColumnNumber:0","@l":"Error","Application":"OER Service"}
{"@t":"2019-04-04T19:47:07.3014708Z","@mt":"xceptionLogId:o957uC0J, ExceptionType:System.NullReferenceException, ExceptionInnerException:, ExceptionMessage:Object reference not set to an instance of an object., ExceptionSeverity:Critical Error, ExceptionFileName:C:\\Clients\\PintLab\\OERService\\OERService\\DataAccess\\CategoryDataAccess.cs, ExceptionMethodName:OERService.DataAccess.CategoryDataAccess+<GetCategories>d__4, ExceptionLineNumber:125, ExceptionColumnNumber:17","@l":"Error","Application":"OER Service"}
{"@t":"2019-04-04T19:51:07.5921700Z","@mt":"Order Service is running","Application":"OER Service"}
{"@t":"2019-04-05T01:56:35.1165771Z","@mt":"Order Service is running","Application":"OER Service"}
